bot:
  map: talery_ant_cave_2
game_window:
  size:
  - 720
  - 1282
  title: TaleryMS
  title_bar_height: 27
  window_height: 0
  window_width: 0
health_monitor:
  add_hp_percent: 0
  add_mp_percent: 0
  enable: false
key:
  aoe_skill: x
  directional_attack: a
  jump: alt
  return_home: ''
  teleport: ''
player_arrow:
  enable: true
rune:
  enable: false
system:
  server: Talery
  skip_party_check: true
talery_anti_cheat:
  enable: false
ui_coords:
  ui_y_start: 724
